const API = 'http://localhost:5000/api';

// =========== NAVIGATION ===========
document.querySelectorAll('.nav-item').forEach(item => {
  item.addEventListener('click', () => {
    const page = item.dataset.page;
    document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
    item.classList.add('active');
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.getElementById('page-' + page).classList.add('active');
    document.getElementById('topbar-title').textContent = item.textContent.trim();
    loadPage(page);
  });
});

// Set date
document.getElementById('topbar-date').textContent = new Date().toLocaleDateString('en-IN', {
  weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
});

function loadPage(page) {
  switch(page) {
    case 'dashboard': loadDashboard(); break;
    case 'members': loadMembers(); break;
    case 'trainers': loadTrainers(); break;
    case 'memberships': loadMemberships(); break;
    case 'equipment': loadEquipment(); break;
    case 'classes': loadClasses(); break;
    case 'attendance': loadAttendance(); break;
    case 'payments': loadPayments(); break;
  }
}

// =========== API HELPER ===========
async function apiFetch(endpoint, method = 'GET', body = null) {
  const token = localStorage.getItem('gym_token');
  const opts = {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { 'Authorization': 'Bearer ' + token } : {})
    }
  };
  if (body) opts.body = JSON.stringify(body);
  try {
    const res = await fetch(API + endpoint, opts);
    if (res.status === 401) {
      localStorage.removeItem('gym_token');
      localStorage.removeItem('gym_user');
      window.location.href = '/login';
      return { success: false };
    }
    return await res.json();
  } catch(e) {
    showToast('Connection error. Is the server running?', 'error');
    return { success: false };
  }
}

// =========== TOAST ===========
function showToast(msg, type = 'info') {
  const tc = document.getElementById('toast-container');
  const t = document.createElement('div');
  const icon = type === 'success' ? '✅' : type === 'error' ? '❌' : 'ℹ️';
  t.className = `toast ${type}`;
  t.innerHTML = `<span>${icon}</span><span>${msg}</span>`;
  tc.appendChild(t);
  setTimeout(() => { t.style.opacity = '0'; t.style.transform = 'translateX(100%)'; t.style.transition = '0.3s'; setTimeout(() => t.remove(), 300); }, 3000);
}


// =========== COPY ID ===========
function copyId(id, btn) {
  navigator.clipboard.writeText(id).then(() => {
    const orig = btn.textContent;
    btn.textContent = 'copied!';
    btn.style.color = 'var(--success)';
    setTimeout(() => { btn.textContent = orig; btn.style.color = 'var(--gray)'; }, 1500);
  });
}

// =========== TABLE FILTER ===========
function filterTable(tableId, query) {
  const rows = document.querySelectorAll(`#${tableId} tbody tr`);
  const q = query.toLowerCase();
  rows.forEach(row => {
    row.style.display = row.textContent.toLowerCase().includes(q) ? '' : 'none';
  });
}

// =========== MODAL ===========
function closeModal() {
  document.getElementById('modal-container').innerHTML = '';
}

async function openModal(type, data = null) {
  const isEdit = !!data;
  let title, formHtml;

  if (type === 'member') {
    title = isEdit ? 'Edit Member' : 'Add New Member';
    // fetch trainers for manager dropdown
    const trRes = await apiFetch('/trainers');
    const trainerOptions = (trRes.data || [])
      .filter(t => t.status === 'Active')
      .map(t => {
        const currentManagerId = data?.managedBy?._id || data?.managedBy || '';
        const sel = currentManagerId === t._id ? 'selected' : '';
        return `<option value="${t._id}" ${sel}>${t.name} — ${t.specialization}</option>`;
      }).join('');
    formHtml = `
      <div class="form-grid">
        ${data ? `<div class="form-group full">
          <label>🔒 Member ID (MongoDB — Cannot be changed)</label>
          <input value="${data._id}" readonly style="opacity:0.6;cursor:not-allowed;background:var(--dark3);font-family:'Courier New',monospace;font-size:13px;letter-spacing:0.5px;"/>
          <small style="color:var(--gray);font-size:10px;margin-top:2px;display:block;">This ID is auto-generated by MongoDB and is permanent</small>
        </div>` : ''}
        <div class="form-group"><label>Full Name *</label><input id="f-name" value="${data?.name || ''}" required/></div>
        <div class="form-group"><label>Email *</label><input id="f-email" type="email" value="${data?.email || ''}" required/></div>
        <div class="form-group"><label>Phone *</label><input id="f-phone" value="${data?.phone || ''}" required/></div>
        <div class="form-group"><label>Age *</label><input id="f-age" type="number" value="${data?.age || ''}" required/></div>
        <div class="form-group"><label>Gender *</label>
          <select id="f-gender">
            <option value="Male" ${data?.gender==='Male'?'selected':''}>Male</option>
            <option value="Female" ${data?.gender==='Female'?'selected':''}>Female</option>
            <option value="Other" ${data?.gender==='Other'?'selected':''}>Other</option>
          </select>
        </div>
        <div class="form-group"><label>Status</label>
          <select id="f-status">
            <option value="Active" ${data?.status==='Active'?'selected':''}>Active</option>
            <option value="Inactive" ${data?.status==='Inactive'?'selected':''}>Inactive</option>
            <option value="Suspended" ${data?.status==='Suspended'?'selected':''}>Suspended</option>
          </select>
        </div>
        <div class="form-group full">
          <label>Assigned Manager (Trainer)</label>
          <select id="f-manager">
            <option value="">— No Manager Assigned —</option>
            ${trainerOptions}
          </select>
        </div>
        <div class="form-group"><label>Membership Expiry</label><input id="f-expiry" type="date" value="${data?.membershipExpiry ? data.membershipExpiry.split('T')[0] : ''}"/></div>
        <div class="form-group"><label>Emergency Contact</label><input id="f-emergency" value="${data?.emergencyContact || ''}"/></div>
        <div class="form-group full"><label>Address</label><textarea id="f-address">${data?.address || ''}</textarea></div>
        <div class="form-group full"><label>Medical Conditions</label><textarea id="f-medical">${data?.medicalConditions || ''}</textarea></div>
      </div>`;
  }

  if (type === 'trainer') {
    title = isEdit ? 'Edit Trainer' : 'Add New Trainer';
    formHtml = `
      <div class="form-grid">
        ${data ? `<div class="form-group full">
          <label>🔒 Trainer ID (MongoDB — Cannot be changed)</label>
          <input value="${data._id}" readonly style="opacity:0.6;cursor:not-allowed;background:var(--dark3);font-family:'Courier New',monospace;font-size:13px;letter-spacing:0.5px;"/>
          <small style="color:var(--gray);font-size:10px;margin-top:2px;display:block;">This ID is auto-generated by MongoDB and is permanent</small>
        </div>` : ''}
        <div class="form-group"><label>Full Name *</label><input id="f-name" value="${data?.name || ''}" required/></div>
        <div class="form-group"><label>Email *</label><input id="f-email" type="email" value="${data?.email || ''}" required/></div>
        <div class="form-group"><label>Phone *</label><input id="f-phone" value="${data?.phone || ''}" required/></div>
        <div class="form-group"><label>Specialization *</label><input id="f-spec" value="${data?.specialization || ''}" placeholder="e.g. Yoga, CrossFit" required/></div>
        <div class="form-group"><label>Experience (years) *</label><input id="f-exp" type="number" value="${data?.experience || ''}" required/></div>
        <div class="form-group"><label>Salary (₹) *</label><input id="f-salary" type="number" value="${data?.salary || ''}" required/></div>
        <div class="form-group"><label>Certification</label><input id="f-cert" value="${data?.certification || ''}"/></div>
        <div class="form-group"><label>Status</label>
          <select id="f-status">
            <option value="Active" ${data?.status==='Active'?'selected':''}>Active</option>
            <option value="Inactive" ${data?.status==='Inactive'?'selected':''}>Inactive</option>
          </select>
        </div>
        <div class="form-group"><label>Rating (0-5)</label><input id="f-rating" type="number" min="0" max="5" value="${data?.rating || 0}"/></div>
      </div>`;
  }

  if (type === 'membership') {
    title = isEdit ? 'Edit Plan' : 'Add Membership Plan';
    formHtml = `
      <div class="form-grid">
        <div class="form-group"><label>Plan Name *</label><input id="f-planName" value="${data?.planName || ''}" required/></div>
        <div class="form-group"><label>Duration (months) *</label><input id="f-duration" type="number" value="${data?.duration || ''}" required/></div>
        <div class="form-group"><label>Price (₹) *</label><input id="f-price" type="number" value="${data?.price || ''}" required/></div>
        <div class="form-group"><label>Max Classes (-1=unlimited)</label><input id="f-maxClasses" type="number" value="${data?.maxClasses ?? -1}"/></div>
        <div class="form-group"><label>Gym Access</label>
          <select id="f-gymAccess">
            <option value="Limited" ${data?.gymAccess==='Limited'?'selected':''}>Limited</option>
            <option value="Full" ${data?.gymAccess==='Full'?'selected':''}>Full</option>
            <option value="24/7" ${data?.gymAccess==='24/7'?'selected':''}>24/7</option>
          </select>
        </div>
        <div class="form-group"><label>Personal Trainer</label>
          <select id="f-personalTrainer">
            <option value="false" ${!data?.personalTrainer?'selected':''}>No</option>
            <option value="true" ${data?.personalTrainer?'selected':''}>Yes</option>
          </select>
        </div>
        <div class="form-group"><label>Status</label>
          <select id="f-status">
            <option value="Active" ${data?.status==='Active'?'selected':''}>Active</option>
            <option value="Inactive" ${data?.status==='Inactive'?'selected':''}>Inactive</option>
          </select>
        </div>
        <div class="form-group full"><label>Description</label><textarea id="f-desc">${data?.description || ''}</textarea></div>
        <div class="form-group full"><label>Features (comma separated)</label><input id="f-features" value="${(data?.features || []).join(', ')}"/></div>
      </div>`;
  }

  if (type === 'equipment') {
    title = isEdit ? 'Edit Equipment' : 'Add Equipment';
    formHtml = `
      <div class="form-grid">
        <div class="form-group"><label>Name *</label><input id="f-name" value="${data?.name || ''}" required/></div>
        <div class="form-group"><label>Category *</label>
          <select id="f-category">
            ${['Cardio','Strength','Flexibility','Free Weights','Machines','Other'].map(c=>`<option value="${c}" ${data?.category===c?'selected':''}>${c}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Brand</label><input id="f-brand" value="${data?.brand || ''}"/></div>
        <div class="form-group"><label>Quantity *</label><input id="f-qty" type="number" value="${data?.quantity || 1}" required/></div>
        <div class="form-group"><label>Condition</label>
          <select id="f-condition">
            ${['Excellent','Good','Fair','Poor','Under Maintenance'].map(c=>`<option value="${c}" ${data?.condition===c?'selected':''}>${c}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Location</label><input id="f-location" value="${data?.location || ''}"/></div>
        <div class="form-group"><label>Purchase Date</label><input id="f-purchaseDate" type="date" value="${data?.purchaseDate ? data.purchaseDate.split('T')[0] : ''}"/></div>
        <div class="form-group"><label>Purchase Price (₹)</label><input id="f-purchasePrice" type="number" value="${data?.purchasePrice || ''}"/></div>
        <div class="form-group"><label>Serial Number</label><input id="f-serial" value="${data?.serialNumber || ''}"/></div>
        <div class="form-group"><label>Last Maintenance</label><input id="f-lastMaint" type="date" value="${data?.lastMaintenanceDate ? data.lastMaintenanceDate.split('T')[0] : ''}"/></div>
        <div class="form-group"><label>Next Maintenance</label><input id="f-nextMaint" type="date" value="${data?.nextMaintenanceDate ? data.nextMaintenanceDate.split('T')[0] : ''}"/></div>
        <div class="form-group"><label>Warranty Expiry</label><input id="f-warranty" type="date" value="${data?.warrantyExpiry ? data.warrantyExpiry.split('T')[0] : ''}"/></div>
      </div>`;
  }

  if (type === 'class') {
    title = isEdit ? 'Edit Class' : 'Add Class';
    formHtml = `
      <div class="form-grid">
        ${data ? `<div class="form-group full">
          <label>🔒 Class ID (MongoDB — Cannot be changed)</label>
          <input value="${data._id}" readonly style="opacity:0.6;cursor:not-allowed;background:var(--dark3);font-family:'Courier New',monospace;font-size:13px;letter-spacing:0.5px;"/>
          <small style="color:var(--gray);font-size:10px;margin-top:2px;display:block;">This ID is auto-generated by MongoDB and is permanent</small>
        </div>` : ''}
        <div class="form-group"><label>Class Name *</label><input id="f-className" value="${data?.className || ''}" required/></div>
        <div class="form-group"><label>Trainer ID *</label><input id="f-trainer" value="${data?.trainer?._id || data?.trainer || ''}" placeholder="Paste trainer ID" required/></div>
        <div class="form-group"><label>Category</label>
          <select id="f-category">
            ${['Yoga','Zumba','HIIT','Pilates','CrossFit','Spinning','Boxing','Other'].map(c=>`<option value="${c}" ${data?.category===c?'selected':''}>${c}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Level</label>
          <select id="f-level">
            ${['Beginner','Intermediate','Advanced','All Levels'].map(l=>`<option value="${l}" ${data?.level===l?'selected':''}>${l}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Day</label>
          <select id="f-day">
            ${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=>`<option value="${d}" ${data?.schedule?.day===d?'selected':''}>${d}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Start Time *</label><input id="f-startTime" type="time" value="${data?.schedule?.startTime || ''}" required/></div>
        <div class="form-group"><label>End Time *</label><input id="f-endTime" type="time" value="${data?.schedule?.endTime || ''}" required/></div>
        <div class="form-group"><label>Capacity *</label><input id="f-capacity" type="number" value="${data?.capacity || ''}" required/></div>
        <div class="form-group"><label>Room</label><input id="f-room" value="${data?.room || ''}"/></div>
        <div class="form-group full"><label>Description</label><textarea id="f-desc">${data?.description || ''}</textarea></div>
      </div>`;
  }

  if (type === 'attendance') {
    title = 'Member Check-In';
    formHtml = `
      <div class="form-grid">
        <div class="form-group full"><label>Member ID *</label><input id="f-memberId" placeholder="Paste member ID here" required/></div>
        <div class="form-group full"><label>Class ID (optional)</label><input id="f-classId" placeholder="Paste class ID (optional)"/></div>
      </div>`;
  }

  if (type === 'payment') {
    title = 'Record Payment';
    formHtml = `
      <div class="form-grid">
        <div class="form-group full"><label>Member ID *</label><input id="f-memberId" placeholder="Paste member ID" required/></div>
        <div class="form-group"><label>Amount (₹) *</label><input id="f-amount" type="number" required/></div>
        <div class="form-group"><label>Payment Method *</label>
          <select id="f-method">
            ${['Cash','Credit Card','Debit Card','UPI','Net Banking'].map(m=>`<option value="${m}">${m}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Payment Type *</label>
          <select id="f-type">
            ${['Membership','Personal Training','Class Fee','Other'].map(t=>`<option value="${t}">${t}</option>`).join('')}
          </select>
        </div>
        <div class="form-group"><label>Status</label>
          <select id="f-status">
            ${['Paid','Pending','Failed','Refunded'].map(s=>`<option value="${s}">${s}</option>`).join('')}
          </select>
        </div>
        <div class="form-group full"><label>Description</label><textarea id="f-desc"></textarea></div>
      </div>`;
  }

  const modal = document.createElement('div');
  modal.className = 'modal-overlay';
  modal.id = 'modal-overlay';
  modal.innerHTML = `
    <div class="modal">
      <div class="modal-header">
        <div class="modal-title">${title}</div>
        <button class="modal-close" onclick="closeModal()">&times;</button>
      </div>
      <div class="modal-body">${formHtml}</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" onclick="closeModal()">Cancel</button>
        <button class="btn btn-primary" onclick="submitForm('${type}', '${data?._id || ''}')">
          ${isEdit ? 'Update' : 'Save'}
        </button>
      </div>
    </div>`;
  modal.addEventListener('click', e => { if(e.target === modal) closeModal(); });
  document.getElementById('modal-container').innerHTML = '';
  document.getElementById('modal-container').appendChild(modal);
}

// =========== SUBMIT FORM ===========
async function submitForm(type, id = '') {
  const isEdit = !!id;
  let body = {};
  let endpoint, method;

  if (type === 'member') {
    const managerId = document.getElementById('f-manager').value;
    body = {
      name: document.getElementById('f-name').value,
      email: document.getElementById('f-email').value,
      phone: document.getElementById('f-phone').value,
      age: +document.getElementById('f-age').value,
      gender: document.getElementById('f-gender').value,
      status: document.getElementById('f-status').value,
      address: document.getElementById('f-address').value,
      medicalConditions: document.getElementById('f-medical').value,
      emergencyContact: document.getElementById('f-emergency').value,
      membershipExpiry: document.getElementById('f-expiry').value || undefined,
      managedBy: managerId || undefined,
    };
    endpoint = isEdit ? `/members/${id}` : '/members';
    method = isEdit ? 'PUT' : 'POST';
  }

  if (type === 'trainer') {
    body = {
      name: document.getElementById('f-name').value,
      email: document.getElementById('f-email').value,
      phone: document.getElementById('f-phone').value,
      specialization: document.getElementById('f-spec').value,
      experience: +document.getElementById('f-exp').value,
      salary: +document.getElementById('f-salary').value,
      certification: document.getElementById('f-cert').value,
      status: document.getElementById('f-status').value,
      rating: +document.getElementById('f-rating').value,
    };
    endpoint = isEdit ? `/trainers/${id}` : '/trainers';
    method = isEdit ? 'PUT' : 'POST';
  }

  if (type === 'membership') {
    const featStr = document.getElementById('f-features').value;
    body = {
      planName: document.getElementById('f-planName').value,
      duration: +document.getElementById('f-duration').value,
      price: +document.getElementById('f-price').value,
      maxClasses: +document.getElementById('f-maxClasses').value,
      gymAccess: document.getElementById('f-gymAccess').value,
      personalTrainer: document.getElementById('f-personalTrainer').value === 'true',
      status: document.getElementById('f-status').value,
      description: document.getElementById('f-desc').value,
      features: featStr ? featStr.split(',').map(f => f.trim()) : [],
    };
    endpoint = isEdit ? `/memberships/${id}` : '/memberships';
    method = isEdit ? 'PUT' : 'POST';
  }

  if (type === 'equipment') {
    body = {
      name: document.getElementById('f-name').value,
      category: document.getElementById('f-category').value,
      brand: document.getElementById('f-brand').value,
      quantity: +document.getElementById('f-qty').value,
      condition: document.getElementById('f-condition').value,
      location: document.getElementById('f-location').value,
      purchaseDate: document.getElementById('f-purchaseDate').value || undefined,
      purchasePrice: +document.getElementById('f-purchasePrice').value || undefined,
      serialNumber: document.getElementById('f-serial').value,
      lastMaintenanceDate: document.getElementById('f-lastMaint').value || undefined,
      nextMaintenanceDate: document.getElementById('f-nextMaint').value || undefined,
      warrantyExpiry: document.getElementById('f-warranty').value || undefined,
    };
    endpoint = isEdit ? `/equipment/${id}` : '/equipment';
    method = isEdit ? 'PUT' : 'POST';
  }

  if (type === 'class') {
    body = {
      className: document.getElementById('f-className').value,
      trainer: document.getElementById('f-trainer').value,
      category: document.getElementById('f-category').value,
      level: document.getElementById('f-level').value,
      schedule: {
        day: document.getElementById('f-day').value,
        startTime: document.getElementById('f-startTime').value,
        endTime: document.getElementById('f-endTime').value,
      },
      capacity: +document.getElementById('f-capacity').value,
      room: document.getElementById('f-room').value,
      description: document.getElementById('f-desc').value,
    };
    endpoint = isEdit ? `/classes/${id}` : '/classes';
    method = isEdit ? 'PUT' : 'POST';
  }

  if (type === 'attendance') {
    body = {
      memberId: document.getElementById('f-memberId').value,
      classId: document.getElementById('f-classId').value || undefined,
    };
    endpoint = '/attendance/checkin';
    method = 'POST';
  }

  if (type === 'payment') {
    body = {
      member: document.getElementById('f-memberId').value,
      amount: +document.getElementById('f-amount').value,
      paymentMethod: document.getElementById('f-method').value,
      paymentType: document.getElementById('f-type').value,
      status: document.getElementById('f-status').value,
      description: document.getElementById('f-desc').value,
    };
    endpoint = '/payments';
    method = 'POST';
  }

  const result = await apiFetch(endpoint, method, body);
  if (result.success) {
    showToast(result.message || 'Saved successfully!', 'success');
    closeModal();
    loadPage(type === 'attendance' ? 'attendance' : type === 'payment' ? 'payments' : type + 's');
  } else {
    showToast(result.message || 'Something went wrong', 'error');
  }
}

// =========== DELETE ===========
async function deleteRecord(type, id) {
  if (!confirm('Are you sure you want to delete this record?')) return;
  const result = await apiFetch(`/${type}/${id}`, 'DELETE');
  if (result.success) {
    showToast('Deleted successfully', 'success');
    loadPage(type);
  } else {
    showToast(result.message || 'Delete failed', 'error');
  }
}

// =========== LOADERS ===========

async function loadDashboard() {
  // fetch everything at once
  const [members, trainers, classes, equipment, payments, attendance, todayAtt, revenue] = await Promise.all([
    apiFetch('/members'),
    apiFetch('/trainers'),
    apiFetch('/classes'),
    apiFetch('/equipment'),
    apiFetch('/payments'),
    apiFetch('/attendance'),
    apiFetch('/attendance/today/count'),
    apiFetch('/payments/revenue/summary'),
  ]);

  // ── Stats ──────────────────────────────────────────────────────────────
  document.getElementById('stat-members').textContent  = members.data?.length || 0;
  document.getElementById('stat-trainers').textContent = trainers.data?.filter(t => t.status === 'Active').length || 0;
  document.getElementById('stat-today').textContent    = todayAtt.data?.count || 0;
  const rev = revenue.data?.summary?.totalRevenue || 0;
  document.getElementById('stat-revenue').textContent  = rev.toLocaleString('en-IN');

  // extra stat cards if they exist on the page
  const statClasses = document.getElementById('stat-classes');
  const statEquip   = document.getElementById('stat-equipment');
  if (statClasses) statClasses.textContent = classes.data?.length || 0;
  if (statEquip)   statEquip.textContent   = equipment.data?.length || 0;

  // ── Recent Members ─────────────────────────────────────────────────────
  const rmEl    = document.getElementById('recent-members');
  const recentM = (members.data || []).slice(-5).reverse();
  rmEl.innerHTML = recentM.length ? recentM.map(m => `
    <div class="recent-item">
      <div class="recent-item-info">
        <div class="recent-item-name">${m.name}</div>
        <div class="recent-item-sub">${m.email} &nbsp;|&nbsp; ${m.phone}</div>
      </div>
      <span class="badge badge-${(m.status||'active').toLowerCase()}">${m.status}</span>
    </div>`).join('') : '<div class="empty-state"><p style="color:var(--gray)">No members yet</p></div>';

  // ── Recent Payments ────────────────────────────────────────────────────
  const rpEl    = document.getElementById('recent-payments');
  const recentP = (payments.data || []).slice(-5).reverse();
  rpEl.innerHTML = recentP.length ? recentP.map(p => `
    <div class="recent-item">
      <div class="recent-item-info">
        <div class="recent-item-name">${p.member?.name || 'Unknown'}</div>
        <div class="recent-item-sub">${p.paymentType} — ${p.paymentMethod}</div>
      </div>
      <span style="color:var(--accent);font-weight:700;font-family:'Barlow Condensed',sans-serif;font-size:18px;">₹${p.amount}</span>
    </div>`).join('') : '<div class="empty-state"><p style="color:var(--gray)">No payments yet</p></div>';

  // ── Recent Attendance ──────────────────────────────────────────────────
  const raEl    = document.getElementById('recent-attendance');
  if (raEl) {
    const recentA = (attendance.data || []).slice(0, 5);
    raEl.innerHTML = recentA.length ? recentA.map(a => `
      <div class="recent-item">
        <div class="recent-item-info">
          <div class="recent-item-name">${a.member?.name || 'Unknown'}</div>
          <div class="recent-item-sub">${a.date} &nbsp;|&nbsp; In: ${new Date(a.checkIn).toLocaleTimeString('en-IN')}</div>
        </div>
        <span style="color:var(--accent2);font-weight:700;font-size:13px;">${a.duration ? a.duration + ' min' : 'Active'}</span>
      </div>`).join('') : '<div class="empty-state"><p style="color:var(--gray)">No attendance yet</p></div>';
  }

  // ── Recent Classes ─────────────────────────────────────────────────────
  const rcEl    = document.getElementById('recent-classes');
  if (rcEl) {
    const recentC = (classes.data || []).slice(0, 5);
    rcEl.innerHTML = recentC.length ? recentC.map(c => `
      <div class="recent-item">
        <div class="recent-item-info">
          <div class="recent-item-name">${c.className}</div>
          <div class="recent-item-sub">${c.trainer?.name || '—'} &nbsp;|&nbsp; ${c.schedule?.day || ''} ${c.schedule?.startTime || ''}</div>
        </div>
        <span style="color:var(--gray);font-size:12px;">${c.enrolledMembers?.length || 0}/${c.capacity}</span>
      </div>`).join('') : '<div class="empty-state"><p style="color:var(--gray)">No classes yet</p></div>';
  }
}

async function loadMembers() {
  const res = await apiFetch('/members');
  const tbody = document.getElementById('members-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="8"><div class="empty-state"><div class="empty-icon">👥</div><h3>No Members Found</h3><p>Add your first member to get started</p></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(m => `
    <tr>
      <td>
        <div style="font-weight:700;font-size:14px;">${m.name}</div>
        <div style="display:flex;align-items:center;gap:6px;margin-top:4px;">
          <span style="font-size:10px;color:var(--gray);font-family:'Courier New',monospace;">${m._id}</span>
          <button onclick="copyId('${m._id}',this)" style="background:var(--dark3);border:none;color:var(--accent2);font-size:10px;padding:1px 6px;border-radius:2px;cursor:pointer;">copy</button>
        </div>
      </td>
      <td>${m.email}</td>
      <td>${m.phone}</td>
      <td>${m.gender}</td>
      <td>
        ${m.managedBy
          ? `<div style="font-weight:600;font-size:13px;color:var(--accent2)">${m.managedBy.name}</div>
             <div style="font-size:11px;color:var(--gray)">${m.managedBy.specialization || ''}</div>`
          : `<span style="color:var(--gray2);font-size:12px;">— Not Assigned —</span>`}
      </td>
      <td><span class="badge badge-${(m.status||'active').toLowerCase()}">${m.status}</span></td>
      <td>${new Date(m.joinDate).toLocaleDateString('en-IN')}</td>
      <td>
        <button class="btn-icon edit" onclick="openModal('member', ${JSON.stringify(m).replace(/"/g, '&quot;')})">✏️</button>
        <button class="btn-icon delete" onclick="deleteRecord('members', '${m._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function loadTrainers() {
  const res = await apiFetch('/trainers');
  const tbody = document.getElementById('trainers-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="7"><div class="empty-state"><div class="empty-icon">🏆</div><h3>No Trainers Found</h3></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(t => `
    <tr>
      <td>
        <div style="font-weight:700;font-size:14px;">${t.name}</div>
        <div style="display:flex;align-items:center;gap:6px;margin-top:4px;">
          <span style="font-size:10px;color:var(--gray);font-family:'Courier New',monospace;">${t._id}</span>
          <button onclick="copyId('${t._id}',this)" style="background:var(--dark3);border:none;color:var(--accent2);font-size:10px;padding:1px 6px;border-radius:2px;cursor:pointer;">copy</button>
        </div>
      </td>
      <td>${t.email}</td>
      <td>${t.specialization}</td>
      <td>${t.experience} yrs</td>
      <td>₹${t.salary.toLocaleString('en-IN')}</td>
      <td><span class="badge badge-${(t.status||'active').toLowerCase()}">${t.status}</span></td>
      <td>
        <button class="btn-icon edit" onclick="openModal('trainer', ${JSON.stringify(t).replace(/"/g, '&quot;')})">✏️</button>
        <button class="btn-icon delete" onclick="deleteRecord('trainers', '${t._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function loadMemberships() {
  const res = await apiFetch('/memberships');
  const tbody = document.getElementById('memberships-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="7"><div class="empty-state"><div class="empty-icon">🎫</div><h3>No Plans Found</h3></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(m => `
    <tr>
      <td><strong>${m.planName}</strong></td>
      <td>${m.duration} month${m.duration > 1 ? 's' : ''}</td>
      <td style="color:var(--accent);font-weight:700;">₹${m.price.toLocaleString('en-IN')}</td>
      <td>${m.gymAccess}</td>
      <td>${m.personalTrainer ? '✅ Yes' : '❌ No'}</td>
      <td><span class="badge badge-${(m.status||'active').toLowerCase()}">${m.status}</span></td>
      <td>
        <button class="btn-icon edit" onclick="openModal('membership', ${JSON.stringify(m).replace(/"/g, '&quot;')})">✏️</button>
        <button class="btn-icon delete" onclick="deleteRecord('memberships', '${m._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function loadEquipment() {
  const res = await apiFetch('/equipment');
  const tbody = document.getElementById('equipment-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="7"><div class="empty-state"><div class="empty-icon">🏗️</div><h3>No Equipment Found</h3></div></td></tr>`;
    return;
  }
  const condBadge = { Excellent: 'excellent', Good: 'good', Fair: 'fair', Poor: 'poor', 'Under Maintenance': 'maintenance' };
  tbody.innerHTML = res.data.map(e => `
    <tr>
      <td><strong>${e.name}</strong></td>
      <td>${e.category}</td>
      <td>${e.brand || '—'}</td>
      <td>${e.quantity}</td>
      <td><span class="badge badge-${condBadge[e.condition] || 'good'}">${e.condition}</span></td>
      <td>${e.location || '—'}</td>
      <td>
        <button class="btn-icon edit" onclick="openModal('equipment', ${JSON.stringify(e).replace(/"/g, '&quot;')})">✏️</button>
        <button class="btn-icon delete" onclick="deleteRecord('equipment', '${e._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function loadClasses() {
  const res = await apiFetch('/classes');
  const tbody = document.getElementById('classes-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="8"><div class="empty-state"><div class="empty-icon">🧘</div><h3>No Classes Found</h3></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(c => `
    <tr>
      <td>
        <div style="font-weight:700;font-size:14px;">${c.className}</div>
        <div style="display:flex;align-items:center;gap:6px;margin-top:4px;">
          <span style="font-size:10px;color:var(--gray);font-family:'Courier New',monospace;">${c._id}</span>
          <button onclick="copyId('${c._id}',this)" style="background:var(--dark3);border:none;color:var(--accent2);font-size:10px;padding:1px 6px;border-radius:2px;cursor:pointer;">copy</button>
        </div>
      </td>
      <td>${c.trainer?.name || '—'}</td>
      <td>${c.schedule?.day || '—'}</td>
      <td>${c.schedule?.startTime || ''} - ${c.schedule?.endTime || ''}</td>
      <td>${c.category || '—'}</td>
      <td>${c.enrolledMembers?.length || 0} / ${c.capacity}</td>
      <td><span class="badge badge-${(c.status||'active').toLowerCase()}">${c.status}</span></td>
      <td>
        <button class="btn-icon edit" onclick="openModal('class', ${JSON.stringify(c).replace(/"/g, '&quot;')})">✏️</button>
        <button class="btn-icon delete" onclick="deleteRecord('classes', '${c._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function loadAttendance() {
  const res = await apiFetch('/attendance');
  const tbody = document.getElementById('attendance-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="6"><div class="empty-state"><div class="empty-icon">📅</div><h3>No Attendance Records</h3></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(a => `
    <tr>
      <td><strong>${a.member?.name || 'Unknown'}</strong><br><small style="color:var(--gray)">${a.member?.email || ''}</small></td>
      <td>${a.date}</td>
      <td>${new Date(a.checkIn).toLocaleTimeString('en-IN')}</td>
      <td>${a.checkOut ? new Date(a.checkOut).toLocaleTimeString('en-IN') : '<button class="btn btn-sm btn-secondary" onclick="checkOut(\''+a._id+'\')">Check Out</button>'}</td>
      <td>${a.duration ? a.duration + ' min' : '—'}</td>
      <td>
        <button class="btn-icon delete" onclick="deleteRecord('attendance', '${a._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

async function checkOut(id) {
  const res = await apiFetch(`/attendance/checkout/${id}`, 'PUT');
  if (res.success) { showToast('Checked out!', 'success'); loadAttendance(); }
  else showToast(res.message, 'error');
}

async function loadPayments() {
  const res = await apiFetch('/payments');
  const tbody = document.getElementById('payments-tbody');
  if (!res.success || !res.data?.length) {
    tbody.innerHTML = `<tr><td colspan="8"><div class="empty-state"><div class="empty-icon">💳</div><h3>No Payments Found</h3></div></td></tr>`;
    return;
  }
  tbody.innerHTML = res.data.map(p => `
    <tr>
      <td style="font-size:11px;color:var(--gray);">${p.invoiceNumber}</td>
      <td><strong>${p.member?.name || 'Unknown'}</strong></td>
      <td style="color:var(--accent);font-weight:700;font-family:'Barlow Condensed',sans-serif;font-size:18px;">₹${p.amount.toLocaleString('en-IN')}</td>
      <td>${p.paymentType}</td>
      <td>${p.paymentMethod}</td>
      <td>${new Date(p.paymentDate).toLocaleDateString('en-IN')}</td>
      <td><span class="badge badge-${(p.status||'paid').toLowerCase()}">${p.status}</span></td>
      <td>
        <button class="btn-icon delete" onclick="deleteRecord('payments', '${p._id}')">🗑️</button>
      </td>
    </tr>`).join('');
}

// =========== INIT ===========
loadDashboard();
